[[redirects]]
  from = "/video"
  to = "/.netlify/functions/video"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/.netlify/functions/assetlinks"
  status = 200
  force = true
